name: DevOps Automation

on:
  push:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Display GitHub Information
  run: |
    echo "Repository : ${{ github.repository }}"
    echo "Branch     : ${{ github.ref_name }}"
    echo "Actor      : ${{ github.actor }}"
    echo "Commit SHA : ${{ github.sha }}"
    echo "Event      : ${{ github.event_name }}"